### ISSUE TITLE
Administrative District area missing

### ISSUE THREAD

**Issue by Hex7CD** [frontiernav/frontiernav-i18n#1]
The "Area" type location "Administrative District" is missing from the map. It's located at the east side of NLA. I believe the same is true for the "Residential District".

EDIT: Oops. Wrong repo. I guess this should have been posted to the Data repo...

EDIT2: Okay, pressing random buttons is bad... I'll just close this and open one at the Data repo. Sorry for the troubles. I'm not used to GitHub. Usually using BitBucket for my private stuff and I've never used the Issues system.

**Comment by jahed** [comment]
These are more "Regions" than "Areas".

![example](http://vignette2.wikia.nocookie.net/xenoblade/images/0/00/XCX-Residential-District-01.png/revision/latest?cb=20150618115940)

I won't be adding them to this repo though, I'm planning to move everything to this one:

https://github.com/frontiernav/frontiernav-data

If you can, just list the translations for anything that's mission in this issue and I'll migrate the names alongside everything else.

**Comment by Hex7CD** [comment]
Oh.. could have sworn it said "Gebiet" (which is German for "Area"). Just checked a Let's Play and it actually says "Region". My bad. Nevertheless, they are still missing from the map. I'll document any such occurences and add them to the issue in the Data repo.
